# Generated by Django 4.2.16 on 2025-12-17 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='input/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output/')),
                ('dot_spacing', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('min_dot_radius', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('max_dot_radius', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)])),
                ('color_mode', models.CharField(choices=[('black_on_white', 'Black dots on white background'), ('white_on_black', 'White dots on black background')], default='black_on_white', max_length=20)),
                ('original_width', models.IntegerField(default=0)),
                ('original_height', models.IntegerField(default=0)),
                ('grid_cols', models.IntegerField(default=0)),
                ('grid_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
